"""
engine/strategy.py — Abstract base class for trading strategies.

This is a stub ready for future implementation.

To add a strategy:
  1. Subclass Strategy
  2. Implement on_bar() — return a Signal based on indicator values
  3. Pass your strategy to BacktestEngine.run()

Example future usage:
    class GoldenCrossStrategy(Strategy):
        def on_bar(self, bar, indicators):
            ma = indicators.get("moving_averages", {})
            if ma.get("golden_cross"):
                return Signal.BUY
            if ma.get("death_cross"):
                return Signal.SELL
            return Signal.HOLD
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class Signal(Enum):
    """Trading signal emitted by a strategy on each bar."""
    BUY  = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


@dataclass
class StrategyContext:
    """Runtime context passed to the strategy on each bar."""
    bar: dict[str, float]               # OHLCV for the current bar
    indicators: dict[str, Any]          # raw values from each indicator
    scores: dict[str, float]            # per-indicator scores
    overall_score: float                # composite indicator score
    pattern_score: float = 5.0          # composite pattern score (5.0 = neutral)
    position: float = 0.0               # current position size (0 = flat)
    cash: float = 100_000.0             # available cash
    portfolio_value: float = 100_000.0  # total portfolio value
    trend_ma: float = 0.0               # short-term trend MA for confirmation filter
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class TradeOrder:
    """An order generated by a strategy."""
    signal: Signal
    quantity: float = 0.0           # 0 = strategy decides sizing
    price: float | None = None      # None = market order
    notes: str = ""


class Strategy(ABC):
    """Base class for all trading strategies.

    Subclasses define entry/exit logic in :meth:`on_bar`.
    Parameters are loaded from the config file or passed directly.
    """

    name: str = "BaseStrategy"

    def __init__(self, params: dict[str, Any] | None = None) -> None:
        self.params: dict[str, Any] = params or {}

    def configure(self, params: dict[str, Any]) -> None:
        """Update strategy parameters (e.g. from config.yaml)."""
        self.params.update(params)

    @abstractmethod
    def on_bar(self, ctx: StrategyContext) -> TradeOrder:
        """Called once per bar during backtesting.

        Args:
            ctx: The current bar context including indicator values and scores.

        Returns:
            A :class:`TradeOrder` indicating what action to take.
        """
        ...

    def on_start(self, metadata: dict[str, Any]) -> None:
        """Called once before the backtest begins. Override if needed."""
        pass

    def on_end(self, metadata: dict[str, Any]) -> None:
        """Called once after the backtest ends. Override if needed."""
        pass
